# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_project_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='picture',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
