# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20170530_2149'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Brand',
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='is_active',
            new_name='is_visible',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='category',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='is_published',
            new_name='is_visible',
        ),
        migrations.AddField(
            model_name='picture',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
