# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_brand_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_order'], 'verbose_name': 'brand', 'verbose_name_plural': 'brands'},
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
