# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20170601_1448'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['picture_order'], 'verbose_name': 'picture', 'verbose_name_plural': 'pictures'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_order'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AddField(
            model_name='picture',
            name='picture_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='project',
            name='project_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
