# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20170601_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_portrait',
            field=models.BooleanField(default=False),
        ),
    ]
