# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_remove_picture_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='is_cover',
        ),
        migrations.RemoveField(
            model_name='picture',
            name='is_portrait',
        ),
    ]
