# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20170602_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('slug', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=False)),
                ('document', models.FileField(upload_to=frontend.models.get_upload_to_path)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Project')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
            },
        ),
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['-created'], 'verbose_name': 'picture', 'verbose_name_plural': 'pictures'},
        ),
        migrations.RemoveField(
            model_name='picture',
            name='picture_order',
        ),
    ]
