# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20170602_0047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='picture',
            options={'ordering': ['picture_order'], 'verbose_name': 'picture', 'verbose_name_plural': 'pictures'},
        ),
        migrations.AddField(
            model_name='picture',
            name='picture_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
