# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20170613_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
