# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_picture_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='are_pictures_inline',
            field=models.BooleanField(default=False),
        ),
    ]
