# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_project_are_pictures_inline'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_fluid',
            field=models.BooleanField(default=False),
        ),
    ]
