# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name='document',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='display_order',
            field=models.IntegerField(choices=[(0, 'Picture, Video, Document'), (1, 'Video, Document, Picture'), (2, 'Document, Picture, Video'), (3, 'Picture, Document, Video'), (4, 'Document, Video, Picture'), (5, 'Video, Picture, Document')], default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='header',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='video',
            name='video_order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
        ),
    ]
