# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 14:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_auto_20170615_1303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['document_order'], 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['video_order'], 'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
    ]
